objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: placeholder-app-label-d46881878f594a2dadfd963843452aab
    name: placeholder-app-name-730040e0c873453f877c10cd07912d1f
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ''
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: placeholder-app-label-d46881878f594a2dadfd963843452aab
    name: placeholder-app-name-730040e0c873453f877c10cd07912d1f
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: placeholder-app-name-730040e0c873453f877c10cd07912d1f:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: wildfly:latest
          namespace: openshift
        incremental: true
      type: Source
    triggers:
    - type: GitHub
      github:
        secret: ${GITHUB_WEBHOOK_SECRET}
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: placeholder-app-label-d46881878f594a2dadfd963843452aab
    name: placeholder-app-name-730040e0c873453f877c10cd07912d1f
  spec:
    replicas: 1
    selector:
      app: placeholder-app-label-d46881878f594a2dadfd963843452aab
      deploymentconfig: placeholder-app-name-730040e0c873453f877c10cd07912d1f
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: placeholder-app-label-d46881878f594a2dadfd963843452aab
          deploymentconfig: placeholder-app-name-730040e0c873453f877c10cd07912d1f
      spec:
        containers:
        - image: placeholder-app-name-730040e0c873453f877c10cd07912d1f:latest
          name: placeholder-app-name-730040e0c873453f877c10cd07912d1f
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - placeholder-app-name-730040e0c873453f877c10cd07912d1f
        from:
          kind: ImageStreamTag
          name: placeholder-app-name-730040e0c873453f877c10cd07912d1f:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: placeholder-app-label-d46881878f594a2dadfd963843452aab
    name: placeholder-app-name-730040e0c873453f877c10cd07912d1f
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: placeholder-app-label-d46881878f594a2dadfd963843452aab
      deploymentconfig: placeholder-app-name-730040e0c873453f877c10cd07912d1f
  status:
    loadBalancer: {}
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  value: https://github.com/dummy_org/dummy_repo
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: The secret used to configure a GitHub webhook
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
apiVersion: v1
kind: Template
